# Generated by Django 4.2.6 on 2023-10-31 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id_movie', models.IntegerField(primary_key=True, serialize=False)),
                ('movie_rank', models.IntegerField()),
                ('movie_score_press', models.DecimalField(decimal_places=1, max_digits=2)),
                ('movie_score_spectator', models.DecimalField(decimal_places=1, max_digits=2)),
                ('nlp_score', models.DecimalField(blank=True, db_column='NLP_score', decimal_places=1, max_digits=2, null=True)),
                ('nlp_rank', models.IntegerField(blank=True, db_column='NLP_rank', null=True)),
            ],
            options={
                'db_table': 'movies',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id_review', models.AutoField(primary_key=True, serialize=False)),
                ('review_score', models.DecimalField(decimal_places=1, max_digits=2)),
                ('review_content', models.TextField(blank=True, null=True)),
                ('id_movie', models.ForeignKey(db_column='id_movie', on_delete=django.db.models.deletion.DO_NOTHING, to='api.movies')),
            ],
            options={
                'db_table': 'reviews',
            },
        ),
    ]
