# Generated by Django 4.2.6 on 2023-10-31 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='movie_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
