# Generated by Django 4.2.6 on 2023-11-05 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_reviews_id_movie_predicted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predicted',
            name='polarity',
        ),
        migrations.RemoveField(
            model_name='predicted',
            name='review_score',
        ),
    ]
