# Generated by Django 4.2.6 on 2023-12-03 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_predicted_polarity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='new_review_score_bert',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
    ]
