# Generated by Django 4.2.6 on 2023-12-03 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_movies_nlp_rank_bert_movies_nlp_score_bert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='nlp_score_bert',
            field=models.DecimalField(blank=True, db_column='NLP_score_bert', decimal_places=3, max_digits=4, null=True),
        ),
    ]
