name: Node.js CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code source
        uses: actions/checkout@v2

      - name: Installation des dépendances
        run: cd backend && pip install -r requirements.txt

      - name: Déploiement sur le serveur FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          local-dir: ./backend/ # Assurez-vous que c'est le bon chemin pour vos fichiers construits
          server: ${{ secrets.FTP_SERVER_BACK }}
          username: ${{ secrets.FTP_USERNAME_BACK }}
          password: ${{ secrets.FTP_PASSWORD_BACK }}
# Ajoutez d'autres étapes de déploiement si nécessaire, par exemple, un déploiement sur un serveur de production, des notifications, etc.
